export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const SELECT_APPOINTMENT = 'SELECT_APPOINTMENT';
export const UPDATE_FORM = 'UPDATE_FORM';

